In [1]:
import pandas as pd

df = pd.read_csv('/Users/alhafeez/Documents/Porto-Tableau/HR-Analysis/data/HRDataset_cleaned.csv')

In [2]:
df["Termd"].mean()

np.float64(0.33440514469453375)

In [3]:
pd.crosstab(df["Department"], df["Termd"], normalize="index") * 100

Termd                          0          1
Department
Admin Offices          77.777778  22.222222
Executive Office      100.000000   0.000000
IT/IS                  80.000000  20.000000
Production             60.287081  39.712919
Sales                  83.870968  16.129032
Software Engineering   63.636364  36.363636

In [4]:
pd.crosstab(df["RecruitmentSource"], df["Termd"], normalize="index") * 100

Termd                            0           1
RecruitmentSource
CareerBuilder            52.173913   47.826087
Diversity Job Fair       44.827586   55.172414
Employee Referral        83.870968   16.129032
Google Search            38.775510   61.224490
Indeed                   75.862069   24.137931
LinkedIn                 76.315789   23.684211
On-line Web application   0.000000  100.000000
Other                    50.000000   50.000000
Website                  92.307692    7.692308

In [5]:
df.groupby("Termd")["Salary"].mean()

Termd
0    70694.033816
1    65690.076923
Name: Salary, dtype: float64

In [6]:
df.groupby("Termd")["EmpSatisfaction"].mean()

Termd
0    3.893720
1    3.884615
Name: EmpSatisfaction, dtype: float64

In [7]:
df.groupby("Termd")["EngagementSurvey"].mean()

Termd
0    4.119807
1    4.090481
Name: EngagementSurvey, dtype: float64

In [8]:
pd.crosstab(df["PerformanceScore"], df["Termd"], normalize="index") * 100

Termd                      0          1
PerformanceScore
Exceeds            78.378378  21.621622
Fully Meets        66.666667  33.333333
Needs Improvement  44.444444  55.555556
PIP                61.538462  38.461538

In [9]:
df.groupby("Termd")["Absences"].mean()

Termd
0     9.830918
1    11.048077
Name: Absences, dtype: float64

In [10]:
df.groupby("Termd")["DaysLateLast30"].mean()

Termd
0    0.289855
1    0.663462
Name: DaysLateLast30, dtype: float64

In [11]:
df["TenureYears"] = (pd.Timestamp("2019-01-01") - pd.to_datetime(df["DateofHire"])).dt.days / 365.25

In [12]:
df.groupby("Termd")["TenureYears"].mean()

Termd
0    5.350461
1    7.010767
Name: TenureYears, dtype: float64